import { useForm, useFieldArray } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { Loader2, Plus, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { useReservations } from '@starcoex-frontend/reservations';
import { useAuth } from '@starcoex-frontend/auth';

const DAYS = [
  { label: '일', value: 0 },
  { label: '월', value: 1 },
  { label: '화', value: 2 },
  { label: '수', value: 3 },
  { label: '목', value: 4 },
  { label: '금', value: 5 },
  { label: '토', value: 6 },
];

const schema = z.object({
  name: z.string().min(1, '템플릿 이름을 입력하세요.'),
  openTime: z.string().min(1, '오픈 시간을 입력하세요.'),
  closeTime: z.string().min(1, '마감 시간을 입력하세요.'),
  slotDuration: z.number().min(10, '최소 10분 이상이어야 합니다.'),
  maxConcurrentBookings: z.number().min(1, '최소 1 이상이어야 합니다.'),
  applicableDays: z.array(z.number()).min(1, '요일을 1개 이상 선택하세요.'),
  // ← 휴식시간 추가
  breaks: z
    .array(
      z.object({
        name: z.string().min(1, '휴식 이름을 입력하세요.'),
        startTime: z.string().min(1, '시작 시간을 입력하세요.'),
        endTime: z.string().min(1, '종료 시간을 입력하세요.'),
      })
    )
    .optional(),
});

type FormValues = z.infer<typeof schema>;

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  serviceId: number | null;
  onSuccess: () => void;
}

export function ServiceTemplateDialog({
  open,
  onOpenChange,
  serviceId,
  onSuccess,
}: Props) {
  const { createScheduleTemplate } = useReservations();
  const { currentUser } = useAuth();

  const form = useForm<FormValues>({
    resolver: zodResolver(schema),
    defaultValues: {
      name: '기본 운영 템플릿',
      openTime: '09:00',
      closeTime: '18:00',
      slotDuration: 60,
      maxConcurrentBookings: 3,
      applicableDays: [1, 2, 3, 4, 5],
      breaks: [],
    },
  });

  const {
    fields: breakFields,
    append: appendBreak,
    remove: removeBreak,
  } = useFieldArray({ control: form.control, name: 'breaks' });

  const onSubmit = async (data: FormValues) => {
    if (!serviceId || !currentUser) return;

    const res = await createScheduleTemplate({
      serviceId,
      name: data.name,
      isActive: true,
      openTime: data.openTime,
      closeTime: data.closeTime,
      slotDuration: data.slotDuration,
      maxConcurrentBookings: data.maxConcurrentBookings,
      applicableDays: data.applicableDays,
      autoGenerateDays: 30,
      createdById: currentUser.id,
      breaks: data.breaks?.length ? data.breaks : undefined, // ← breaks 전달
    });

    if (res.success) {
      toast.success('템플릿이 생성되었습니다.');
      onOpenChange(false);
      onSuccess();
      form.reset();
    } else {
      toast.error(res.error?.message ?? '템플릿 생성에 실패했습니다.');
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>운영 템플릿 생성</DialogTitle>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            {/* 템플릿 이름 */}
            <FormField
              control={form.control}
              name="name"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>템플릿 이름</FormLabel>
                  <FormControl>
                    <Input {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            {/* 오픈/마감 시간 */}
            <div className="grid grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="openTime"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>오픈 시간</FormLabel>
                    <FormControl>
                      <Input type="time" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="closeTime"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>마감 시간</FormLabel>
                    <FormControl>
                      <Input type="time" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            {/* 슬롯/동시 예약 */}
            <div className="grid grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="slotDuration"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>슬롯 단위 (분)</FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        {...field}
                        onChange={(e) => field.onChange(Number(e.target.value))}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="maxConcurrentBookings"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>동시 예약 수</FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        {...field}
                        onChange={(e) => field.onChange(Number(e.target.value))}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            {/* 적용 요일 */}
            <FormField
              control={form.control}
              name="applicableDays"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>적용 요일</FormLabel>
                  <div className="flex gap-3 pt-1">
                    {DAYS.map((day) => (
                      <div
                        key={day.value}
                        className="flex flex-col items-center gap-1"
                      >
                        <Checkbox
                          checked={field.value.includes(day.value)}
                          onCheckedChange={(checked) => {
                            const next = checked
                              ? [...field.value, day.value]
                              : field.value.filter((d) => d !== day.value);
                            field.onChange(next);
                          }}
                        />
                        <span className="text-xs">{day.label}</span>
                      </div>
                    ))}
                  </div>
                  <FormMessage />
                </FormItem>
              )}
            />

            {/* ← 휴식시간 설정 */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <FormLabel>휴식 시간</FormLabel>
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={() =>
                    appendBreak({
                      name: '점심시간',
                      startTime: '12:00',
                      endTime: '13:00',
                    })
                  }
                >
                  <Plus className="mr-1 size-3" />
                  휴식 추가
                </Button>
              </div>
              <p className="text-muted-foreground text-xs">
                슬롯 자동 생성 시 해당 시간대는 예약 불가 처리됩니다.
              </p>
              {breakFields.length === 0 && (
                <p className="text-muted-foreground text-xs">
                  등록된 휴식 시간이 없습니다.
                </p>
              )}
              {breakFields.map((field, index) => (
                <div
                  key={field.id}
                  className="flex items-end gap-2 rounded-md border p-3"
                >
                  <FormField
                    control={form.control}
                    name={`breaks.${index}.name`}
                    render={({ field }) => (
                      <FormItem className="flex-1">
                        <FormLabel className="text-xs">이름</FormLabel>
                        <FormControl>
                          <Input {...field} placeholder="점심시간" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name={`breaks.${index}.startTime`}
                    render={({ field }) => (
                      <FormItem className="flex-1">
                        <FormLabel className="text-xs">시작</FormLabel>
                        <FormControl>
                          <Input type="time" {...field} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name={`breaks.${index}.endTime`}
                    render={({ field }) => (
                      <FormItem className="flex-1">
                        <FormLabel className="text-xs">종료</FormLabel>
                        <FormControl>
                          <Input type="time" {...field} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    className="mb-0.5 size-9 text-destructive hover:text-destructive"
                    onClick={() => removeBreak(index)}
                  >
                    <Trash2 className="size-4" />
                  </Button>
                </div>
              ))}
            </div>

            <DialogFooter>
              <Button
                variant="outline"
                type="button"
                onClick={() => onOpenChange(false)}
              >
                취소
              </Button>
              <Button type="submit" disabled={form.formState.isSubmitting}>
                {form.formState.isSubmitting && (
                  <Loader2 className="mr-2 size-4 animate-spin" />
                )}
                생성
              </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
