import type { ApiResponse } from '../types';

// ============================================================================
// 공통 Enum
// ============================================================================

export type ReservationStatus =
  | 'PAYMENT_PENDING'
  | 'PAYMENT_FAILED'
  | 'PAYMENT_EXPIRED'
  | 'PENDING_APPROVAL'
  | 'CONFIRMED'
  | 'CHECKED_IN'
  | 'IN_PROGRESS'
  | 'COMPLETED'
  | 'NO_SHOW'
  | 'CANCELLED'
  | 'REFUND_REQUESTED'
  | 'REFUND_PROCESSING'
  | 'REFUNDED'
  | 'PARTIAL_REFUNDED';

export type ConfirmationType = 'AUTO' | 'MANUAL';

export type ApprovalStatus = 'PENDING' | 'APPROVED' | 'REJECTED' | 'EXPIRED';

export type ResourceType =
  | 'BAY'
  | 'WASH_MACHINE'
  | 'WASH_STATION'
  | 'FUEL_PUMP'
  | 'STAFF'
  | 'ROOM'
  | 'OTHER';

export type SlotStatus =
  | 'AVAILABLE'
  | 'RESERVED'
  | 'PENDING'
  | 'BLOCKED'
  | 'EXPIRED';

export type WalkInStatus =
  | 'WAITING'
  | 'CALLED'
  | 'IN_SERVICE'
  | 'COMPLETED'
  | 'CANCELLED'
  | 'NO_SHOW';

export type FuelType = 'GASOLINE' | 'DIESEL' | 'PREMIUM_GASOLINE' | 'KEROSENE';

export type FuelWalkInStatus =
  | 'WAITING'
  | 'PAYMENT_PENDING'
  | 'READY'
  | 'IN_SERVICE'
  | 'COMPLETED'
  | 'PAYMENT_DUE'
  | 'CANCELLED'
  | 'REFUND_PENDING';

export type PackageStatus =
  | 'WAITING'
  | 'PAID'
  | 'FUEL_DONE'
  | 'WASH_DONE'
  | 'COMPLETED'
  | 'CANCELLED'
  | 'PARTIAL_DONE';

export type HeatingOilFuelType = 'KEROSENE';

export type HeatingOilOrderType = 'STANDARD' | 'URGENT';

export type HeatingOilDeliveryStatus =
  | 'PENDING'
  | 'CONFIRMED'
  | 'DRIVER_ASSIGNED'
  | 'DISPATCHED'
  | 'ARRIVED'
  | 'COMPLETED'
  | 'CANCELLED'
  | 'REFUND_REQUESTED'
  | 'REFUNDED';

export type SlotGenerationType = 'AUTO' | 'MANUAL';

export type ReservableServiceType =
  | 'CAR_WASH'
  | 'CAR_CARE'
  | 'CAR_REPAIR'
  | 'OIL_CHANGE'
  | 'FUEL'
  | 'EV_CHARGING'
  | 'TABLE'
  | 'ROOM'
  | 'PICKUP'
  | 'DELIVERY'
  | 'CONSULTATION'
  | 'EVENT';

// ============================================================================
// 공통 에러
// ============================================================================

export interface ReservationErrorInfo {
  code?: string | null;
  message: string;
  details?: string | null;
}

// ============================================================================
// Reservation 엔티티 (schema 기준)
// ============================================================================

export interface Reservation {
  id: number;
  reservationNumber: string;
  storeId: number;
  serviceId: number;
  timeSlotId?: number | null;
  resourceId?: number | null;
  vehicleId?: number | null;
  reservedDate: string;
  reservedStartTime: string;
  reservedEndTime: string;
  paymentExpiresAt?: string | null;
  autoCancel: boolean;
  userId?: number | null;
  guestEmail?: string | null;
  customerInfo: Record<string, any>;
  status: ReservationStatus;
  confirmationType: ConfirmationType;
  isWalkIn: boolean;
  partySize: number;
  specialRequests?: string | null;
  /** 결제 ID (단일) */
  paymentId?: number | null;
  paymentConfirmed: boolean;
  appliedRefundPolicy?: Record<string, any> | null;
  confirmedAt?: string | null;
  checkedInAt?: string | null;
  serviceStartedAt?: string | null;
  completedAt?: string | null;
  cancelledAt?: string | null;
  notes?: string | null;
  metadata?: Record<string, any> | null;
  createdById?: number | null;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
  store?: { id: number } | null;
  user?: { id: number } | null;
  vehicle?: { id: number } | null;
}

export interface ReservationTimeSlot {
  id: number;
  serviceId: number;
  resourceId?: number | null;
  date: string;
  startTime: string;
  endTime: string;
  status: SlotStatus;
  maxCapacity: number;
  currentBookings: number;
  pendingBookings: number;
  priceMultiplier?: number | null;
  bookingDeadline?: string | null;
  isAutoGenerated: boolean;
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
}

export interface ServiceResource {
  id: number;
  serviceId: number;
  name: string;
  code: string;
  type: ResourceType;
  capacity: number;
  isActive: boolean;
  isAvailable: boolean;
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
}

export interface ScheduleTemplate {
  id: number;
  serviceId: number;
  name: string;
  isActive: boolean;
  applicableDays: number[];
  openTime: string;
  closeTime: string;
  slotDuration?: number | null;
  maxConcurrentBookings: number;
  autoGenerateDays: number;
  createdById: number;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
}

export interface ScheduleBlockedDate {
  id: number;
  serviceId: number;
  date: string;
  reason?: string | null;
  isFullDay: boolean;
  blockedStartTime?: string | null;
  blockedEndTime?: string | null;
  createdById: number;
  createdAt: string;
}

export interface WalkIn {
  id: number;
  storeId: number;
  serviceId: number;
  resourceId?: number | null;
  userId?: number | null;
  customerName?: string | null;
  customerPhone?: string | null;
  vehicleId?: number | null;
  packageId?: number | null;
  /** 결제 확인 여부 (schema 기준) */
  paymentConfirmed: boolean;
  status: WalkInStatus;
  waitingOrder: number;
  estimatedWaitMinutes?: number | null;
  arrivedAt: string;
  calledAt?: string | null;
  startedAt?: string | null;
  completedAt?: string | null;
  cancelledAt?: string | null;
  notes?: string | null;
  metadata?: Record<string, any> | null;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
}

export interface ReservationApproval {
  id: number;
  reservationId: number;
  status: ApprovalStatus;
  reviewedBy?: number | null;
  reviewedAt?: string | null;
  reason?: string | null;
  autoApproveAt?: string | null;
  createdAt: string;
  updatedAt: string;
}

// ============================================================================
// FuelWalkIn 엔티티 (schema 기준)
// ============================================================================

export interface FuelWalkIn {
  id: number;
  storeId: number;
  resourceId?: number | null;
  userId?: number | null;
  customerName?: string | null;
  customerPhone?: string | null;
  vehicleId?: number | null;
  /** 상품 ID (apps/products 참조) */
  productId?: number | null;
  fuelType?: string | null;
  requestedAmount?: number | null;
  actualAmount?: number | null;
  literAmount?: number | null;
  unitPrice?: number | null;
  /** 선결제 여부 */
  isPrepaid: boolean;
  /** 결제 ID (단일) */
  paymentId?: number | null;
  paymentConfirmed: boolean;
  packageId?: number | null;
  status: FuelWalkInStatus;
  arrivedAt: string;
  paymentDoneAt?: string | null;
  startedAt?: string | null;
  completedAt?: string | null;
  cancelledAt?: string | null;
  notes?: string | null;
  metadata?: Record<string, any> | null;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
}

export interface FuelWalkInPackage {
  id: number;
  storeId: number;
  userId?: number | null;
  customerName?: string | null;
  customerPhone?: string | null;
  vehicleId?: number | null;
  includesFuel: boolean;
  includesWash: boolean;
  washServiceId?: number | null;
  /** 선결제 여부 */
  isPrepaid: boolean;
  /** 결제 ID (단일) */
  paymentId?: number | null;
  paymentConfirmed: boolean;
  status: PackageStatus;
  arrivedAt: string;
  completedAt?: string | null;
  cancelledAt?: string | null;
  notes?: string | null;
  metadata?: Record<string, any> | null;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
}

// ============================================================================
// HeatingOilDelivery 엔티티 (schema 기준)
// ============================================================================

export interface HeatingOilDelivery {
  id: number;
  storeId: number;
  deliveryNumber: string;
  /** 상품 ID (apps/products 참조) */
  productId?: number | null;
  userId?: number | null;
  customerName: string;
  customerPhone: string;
  guestEmail?: string | null;
  deliveryAddress: string;
  deliveryAddressDetail?: string | null;
  deliveryLatitude?: number | null;
  deliveryLongitude?: number | null;
  fuelType: string;
  orderType: HeatingOilOrderType;
  requestedLiters: number;
  actualLiters?: number | null;
  unitPrice?: number | null;
  tankCapacity?: number | null;
  tankCurrentLevel?: number | null;
  /** 결제 ID (단일) */
  paymentId?: number | null;
  paymentConfirmed: boolean;
  status: HeatingOilDeliveryStatus;
  scheduledDate: string;
  scheduledTimeSlot: string;
  isUrgent: boolean;
  urgentRequestedAt?: string | null;
  urgentReason?: string | null;
  driverId?: number | null;
  driverAssignedAt?: string | null;
  confirmedAt?: string | null;
  dispatchedAt?: string | null;
  arrivedAt?: string | null;
  completedAt?: string | null;
  cancelledAt?: string | null;
  notes?: string | null;
  metadata?: Record<string, any> | null;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
}

// ============================================================================
// ReservableService 엔티티 (schema 기준)
// ============================================================================

export interface ReservableService {
  id: number;
  storeId: number;
  name: string;
  type: ReservableServiceType | string;
  /** apps/stores ServiceType 코드 */
  serviceTypeCode?: string | null;
  description?: string | null;
  confirmationType: ConfirmationType;
  slotGenerationType: SlotGenerationType;
  requiresPayment: boolean;
  allowWalkIn: boolean;
  operatingHours: Record<string, any>;
  slotDuration: number;
  maxAdvanceDays: number;
  minAdvanceHours: number;
  basePrice: number;
  depositRate: number;
  refundPolicyId: number;
  isActive: boolean;
  isAvailable: boolean;
  createdById: number;
  updatedById: number;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
}

// ============================================================================
// Input 타입 — Reservation
// ============================================================================

export interface FindReservableServicesInput {
  storeId?: number;
  type?: string;
  isActive?: boolean;
}

export interface FindReservableServicesOutput {
  success: boolean;
  services: ReservableService[];
}

export interface FindReservationsInput {
  storeId?: number;
  userId?: number;
  vehicleId?: number;
  resourceId?: number;
  status?: ReservationStatus;
  isWalkIn?: boolean;
  dateFrom?: string;
  dateTo?: string;
  page?: number;
  limit?: number;
}

export interface CreateReservationInput {
  storeId: number;
  serviceId: number;
  serviceIds: number[];
  timeSlotId?: number;
  reservedDate: string;
  reservedStartTime: string;
  reservedEndTime: string;
  autoCancel?: boolean;
  userId?: number;
  guestEmail?: string;
  customerInfo: Record<string, any>;
  status?: ReservationStatus;
  partySize?: number;
  specialRequests?: string;
  notes?: string;
  metadata?: Record<string, any>;
  createdById?: number;
  resourceId?: number;
  vehicleId?: number;
}

export interface UpdateReservationStatusInput {
  reservationId: number;
  storeId?: number;
  serviceId?: number;
  timeSlotId?: number;
  reservedDate?: string;
  reservedStartTime?: string;
  reservedEndTime?: string;
  autoCancel?: boolean;
  userId?: number;
  guestEmail?: string;
  customerInfo?: Record<string, any>;
  status?: ReservationStatus;
  partySize?: number;
  specialRequests?: string;
  notes?: string;
  metadata?: Record<string, any>;
  resourceId?: number;
  vehicleId?: number;
  reason?: string;
}

export interface CancelReservationInput {
  reservationId: number;
  cancellationReason: string;
}

export interface CheckInReservationInput {
  reservationId: number;
  notes?: string;
}

export interface CheckOutReservationInput {
  reservationId: number;
  notes?: string;
}

export interface ReviewReservationApprovalInput {
  reservationId: number;
  status: ApprovalStatus;
  reason?: string;
}

export interface CreateWalkInInput {
  storeId: number;
  serviceId: number;
  resourceId?: number;
  userId?: number;
  customerName?: string;
  customerPhone?: string;
  vehicleId?: number;
  notes?: string;
  metadata?: Record<string, any>;
}

export interface UpdateWalkInStatusInput {
  walkInId: number;
  status: WalkInStatus;
  notes?: string;
}

export interface GenerateSlotsInput {
  serviceId: number;
  fromDate: string;
  toDate: string;
  templateId?: number;
}

export interface CreateScheduleTemplateInput {
  serviceId: number;
  name: string;
  isActive?: boolean;
  applicableDays: number[];
  openTime: string;
  closeTime: string;
  slotDuration?: number;
  maxConcurrentBookings?: number;
  autoGenerateDays?: number;
  createdById: number;
  breaks?: { name: string; startTime: string; endTime: string }[];
}

export interface CreateScheduleBlockedDateInput {
  serviceId: number;
  date: string;
  reason?: string;
  isFullDay?: boolean;
  blockedStartTime?: string;
  blockedEndTime?: string;
  // createdById: number;
}

// ← 신규 추가
export interface UpdateScheduleBlockedDateInput {
  id: number;
  reason?: string;
  isFullDay?: boolean;
  blockedStartTime?: string;
  blockedEndTime?: string;
}

// ← 신규 추가
export interface FindScheduleBlockedDatesInput {
  serviceId: number;
  dateFrom?: string;
  dateTo?: string;
}

// ← 신규 추가
export interface FindScheduleBlockedDatesOutput {
  success: boolean;
  blockedDates: ScheduleBlockedDate[];
  total: number;
}

export interface CreateServiceResourceInput {
  serviceId: number;
  name: string;
  code: string;
  type: ResourceType;
  capacity?: number;
  isActive?: boolean;
  isAvailable?: boolean;
  notes?: string;
}

export interface UpdateServiceResourceInput {
  id: number;
  isActive?: boolean;
  isAvailable?: boolean;
  notes?: string;
}

// ============================================================================
// Input 타입 — FuelWalkIn (schema 기준)
// ============================================================================

export interface CreateFuelWalkInInput {
  storeId: number;
  resourceId?: number;
  vehicleId?: number;
  userId?: number;
  /** 상품 ID (apps/products 참조) */
  productId?: number;
  customerName?: string;
  customerPhone?: string;
  fuelType?: string;
  requestedAmount?: number;
  isPrepaid?: boolean;
  notes?: string;
  metadata?: Record<string, any>;
}

export interface AttachFuelPaymentInput {
  fuelWalkInId: number;
  paymentId: number;
  paidAmount: number;
}

export interface CompleteFuelWalkInInput {
  fuelWalkInId: number;
  /** 재고 차감용 상품 ID */
  productId: number;
  actualAmount: number;
  literAmount: number;
  unitPrice: number;
}

export interface UpdateFuelWalkInStatusInput {
  fuelWalkInId: number;
  status: FuelWalkInStatus;
}

export interface CreateFuelWalkInPackageInput {
  storeId: number;
  userId?: number;
  customerName?: string;
  customerPhone?: string;
  vehicleId?: number;
  includesFuel?: boolean;
  includesWash?: boolean;
  washServiceId?: number;
  isPrepaid?: boolean;
  notes?: string;
  metadata?: Record<string, any>;
}

export interface AttachPackagePaymentInput {
  packageId: number;
  paymentId: number;
  paidAmount: number;
}

export interface UpdatePackageStatusInput {
  packageId: number;
  status: PackageStatus;
}

// ============================================================================
// Input 타입 — HeatingOilDelivery (schema 기준)
// ============================================================================

export interface CreateHeatingOilDeliveryInput {
  storeId: number;
  /** 상품 ID (apps/products 참조) */
  productId?: number;
  userId?: number;
  customerName: string;
  customerPhone: string;
  guestEmail?: string;
  deliveryAddress: string;
  deliveryAddressDetail?: string;
  fuelType: string;
  orderType?: HeatingOilOrderType;
  requestedLiters: number;
  tankCapacity?: number;
  tankCurrentLevel?: number;
  scheduledDate: string;
  scheduledTimeSlot: string;
  isUrgent?: boolean;
  urgentReason?: string;
  notes?: string;
  metadata?: Record<string, any>;
}

export interface AssignDriverInput {
  deliveryId: number;
  driverId: number;
}

export interface UpdateHeatingOilDeliveryStatusInput {
  deliveryId: number;
  status: HeatingOilDeliveryStatus;
  reason?: string;
}

export interface CompleteHeatingOilDeliveryInput {
  deliveryId: number;
  /** 재고 차감용 상품 ID */
  productId: number;
  actualLiters: number;
  unitPrice: number;
  notes?: string;
}

// ============================================================================
// Input 타입 — ReservableService (schema 기준)
// ============================================================================

export interface CreateReservableServiceInput {
  storeId: number;
  name: string;
  type: ReservableServiceType | string;
  serviceTypeCode?: string;
  description?: string;
  confirmationType?: ConfirmationType;
  slotGenerationType?: SlotGenerationType;
  requiresPayment?: boolean;
  allowWalkIn?: boolean;
  operatingHours: Record<string, any>;
  slotDuration: number;
  maxAdvanceDays?: number;
  minAdvanceHours?: number;
  basePrice: number;
  depositRate?: number;
  refundPolicyId: number;
  isActive?: boolean;
  isAvailable?: boolean;
  createdById: number;
  updatedById?: number;
}

export interface UpdateReservableServiceInput {
  id: number;
  name?: string;
  type?: ReservableServiceType | string;
  serviceTypeCode?: string;
  description?: string;
  confirmationType?: ConfirmationType;
  slotGenerationType?: SlotGenerationType;
  requiresPayment?: boolean;
  allowWalkIn?: boolean;
  operatingHours?: Record<string, any>;
  slotDuration?: number;
  maxAdvanceDays?: number;
  minAdvanceHours?: number;
  basePrice?: number;
  depositRate?: number;
  refundPolicyId?: number;
  isActive?: boolean;
  isAvailable?: boolean;
  updatedById: number;
}

export interface ReservableServiceOutput {
  success: boolean;
  service?: ReservableService;
  message: string;
}

export interface DeleteReservableServiceOutput {
  success: boolean;
  message: string;
}

// ============================================================================
// RefundPolicy
// ============================================================================

export interface RefundPolicy {
  id: number;
  name: string;
  description?: string | null;
  refundRules: Record<string, any>;
  allowRefund: boolean;
  minimumRefundAmount: number;
  refundFee: number;
  noRefundConditions?: Record<string, any> | null;
  createdById: number;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
}

export interface FindRefundPoliciesOutput {
  success: boolean;
  refundPolicies: RefundPolicy[];
}

export interface RefundPolicyOutput {
  success: boolean;
  refundPolicy?: RefundPolicy;
  message: string;
}

export interface CreateRefundPolicyInput {
  name: string;
  description?: string;
  refundRules: Record<string, any>;
  allowRefund?: boolean;
  minimumRefundAmount?: number;
  refundFee?: number;
  noRefundConditions?: Record<string, any>;
}

export interface UpdateRefundPolicyInput {
  id: number;
  name?: string;
  description?: string;
  refundRules?: Record<string, any>;
  allowRefund?: boolean;
  minimumRefundAmount?: number;
  refundFee?: number;
  noRefundConditions?: Record<string, any>;
}

// ============================================================================
// Output 타입
// ============================================================================

export interface DeleteReservationOutput {
  success: boolean;
  message: string;
}

export interface CreateReservationOutput {
  success?: boolean | null;
  error?: ReservationErrorInfo | null;
  reservation?: Reservation | null;
  reservations?: Reservation[] | null;
  message?: string | null;
}

export interface UpdateReservationOutput {
  success?: boolean | null;
  error?: ReservationErrorInfo | null;
  reservation?: Reservation | null;
  message?: string | null;
}

export interface CancelReservationOutput {
  success?: boolean | null;
  error?: ReservationErrorInfo | null;
  reservation?: Reservation | null;
  message?: string | null;
  refundRequested?: boolean | null;
}

export interface CheckInReservationOutput {
  success?: boolean | null;
  error?: ReservationErrorInfo | null;
  reservation?: Reservation | null;
  message?: string | null;
}

export interface CheckOutReservationOutput {
  success?: boolean | null;
  error?: ReservationErrorInfo | null;
  reservation?: Reservation | null;
  message?: string | null;
}

export interface ReservationApprovalOutput {
  success?: boolean | null;
  error?: ReservationErrorInfo | null;
  approval?: ReservationApproval | null;
  message?: string | null;
}

export interface FindReservationsOutput {
  success?: boolean | null;
  error?: ReservationErrorInfo | null;
  reservations?: Reservation[] | null;
  total?: number | null;
  page?: number | null;
  limit?: number | null;
  totalPages?: number | null;
}

export interface WalkInOutput {
  success?: boolean | null;
  error?: ReservationErrorInfo | null;
  walkIn?: WalkIn | null;
  message?: string | null;
}

export interface GenerateSlotsOutput {
  success?: boolean | null;
  error?: ReservationErrorInfo | null;
  slots?: ReservationTimeSlot[] | null;
  generatedCount?: number | null;
  message?: string | null;
}

export interface ScheduleTemplateOutput {
  success?: boolean | null;
  error?: ReservationErrorInfo | null;
  template?: ScheduleTemplate | null;
  message?: string | null;
}

export interface ServiceResourceOutput {
  success?: boolean | null;
  error?: ReservationErrorInfo | null;
  resource?: ServiceResource | null;
  message?: string | null;
}

export interface ScheduleBlockedDateOutput {
  success?: boolean | null;
  error?: ReservationErrorInfo | null;
  blockedDate?: ScheduleBlockedDate | null;
  message?: string | null;
}

export interface FuelWalkInOutput {
  success?: boolean | null;
  error?: ReservationErrorInfo | null;
  fuelWalkIn?: FuelWalkIn | null;
  message?: string | null;
}

export interface FuelWalkInPackageOutput {
  success?: boolean | null;
  error?: ReservationErrorInfo | null;
  package?: FuelWalkInPackage | null;
  message?: string | null;
}

export interface FindFuelWalkInsOutput {
  success?: boolean | null;
  error?: ReservationErrorInfo | null;
  fuelWalkIns?: FuelWalkIn[] | null;
  total?: number | null;
}

export interface HeatingOilDeliveryOutput {
  success?: boolean | null;
  error?: ReservationErrorInfo | null;
  delivery?: HeatingOilDelivery | null;
  message?: string | null;
}

export interface FindHeatingOilDeliveriesOutput {
  success?: boolean | null;
  error?: ReservationErrorInfo | null;
  deliveries?: HeatingOilDelivery[] | null;
  total?: number | null;
}

// ============================================================================
// 서비스 인터페이스
// ============================================================================

export interface IReservationsService {
  // ─── Reservation Queries ───
  getReservationById(id: number): Promise<ApiResponse<Reservation>>;
  listReservations(
    input: FindReservationsInput
  ): Promise<ApiResponse<FindReservationsOutput>>;
  findAvailableSlots(
    serviceId: number,
    date: string
  ): Promise<ApiResponse<ReservationTimeSlot[]>>;
  findServiceResources(
    serviceId: number
  ): Promise<ApiResponse<ServiceResource[]>>;
  findScheduleTemplates(
    serviceId: number
  ): Promise<ApiResponse<ScheduleTemplate[]>>;
  findScheduleBlockedDates(
    input: FindScheduleBlockedDatesInput // ← 인자 변경
  ): Promise<ApiResponse<FindScheduleBlockedDatesOutput>>; // ← 반환 타입 변경
  createScheduleBlockedDate(
    input: CreateScheduleBlockedDateInput
  ): Promise<ApiResponse<ScheduleBlockedDateOutput>>;
  updateScheduleBlockedDate( // ← 신규
    input: UpdateScheduleBlockedDateInput
  ): Promise<ApiResponse<ScheduleBlockedDateOutput>>;
  deleteScheduleBlockedDate(
    id: number
  ): Promise<ApiResponse<ScheduleBlockedDateOutput>>;
  bulkDeleteScheduleBlockedDates( // ← 신규
    ids: number[]
  ): Promise<ApiResponse<ScheduleBlockedDateOutput>>;
  findWalkIns(input: {
    storeId?: number;
    serviceId?: number;
    status?: WalkInStatus;
  }): Promise<ApiResponse<{ walkIns?: WalkIn[]; total?: number }>>;
  findReservableServices(
    input: FindReservableServicesInput
  ): Promise<ApiResponse<FindReservableServicesOutput>>;
  findRefundPolicies(): Promise<ApiResponse<FindRefundPoliciesOutput>>;

  // ─── FuelWalkIn Queries ───
  findFuelWalkIns(input: {
    storeId?: number;
    status?: FuelWalkInStatus;
  }): Promise<ApiResponse<FindFuelWalkInsOutput>>;

  // ─── HeatingOilDelivery Queries ───
  findHeatingOilDeliveries(input: {
    storeId?: number;
    status?: HeatingOilDeliveryStatus;
    isUrgent?: boolean;
    driverId?: number;
  }): Promise<ApiResponse<FindHeatingOilDeliveriesOutput>>;

  // ─── Reservation Mutations ───
  createReservation(
    input: CreateReservationInput
  ): Promise<ApiResponse<CreateReservationOutput>>;
  updateReservationStatus(
    input: UpdateReservationStatusInput
  ): Promise<ApiResponse<UpdateReservationOutput>>;
  cancelReservation(
    input: CancelReservationInput
  ): Promise<ApiResponse<CancelReservationOutput>>;
  checkInReservation(
    input: CheckInReservationInput
  ): Promise<ApiResponse<CheckInReservationOutput>>;
  checkOutReservation(
    input: CheckOutReservationInput
  ): Promise<ApiResponse<CheckOutReservationOutput>>;
  reviewReservationApproval(
    input: ReviewReservationApprovalInput
  ): Promise<ApiResponse<ReservationApprovalOutput>>;
  createWalkIn(input: CreateWalkInInput): Promise<ApiResponse<WalkInOutput>>;
  updateWalkInStatus(
    input: UpdateWalkInStatusInput
  ): Promise<ApiResponse<WalkInOutput>>;
  generateSlots(
    input: GenerateSlotsInput
  ): Promise<ApiResponse<GenerateSlotsOutput>>;
  createScheduleTemplate(
    input: CreateScheduleTemplateInput
  ): Promise<ApiResponse<ScheduleTemplateOutput>>;
  createScheduleBlockedDate(
    input: CreateScheduleBlockedDateInput
  ): Promise<ApiResponse<ScheduleBlockedDateOutput>>;
  createServiceResource(
    input: CreateServiceResourceInput
  ): Promise<ApiResponse<ServiceResourceOutput>>;
  updateServiceResource(
    input: UpdateServiceResourceInput
  ): Promise<ApiResponse<ServiceResourceOutput>>;

  // ─── Reservation 삭제/비활성화 ───
  deleteReservation(
    reservationId: number
  ): Promise<ApiResponse<DeleteReservationOutput>>;
  bulkDeleteReservations(
    reservationIds: number[]
  ): Promise<ApiResponse<DeleteReservationOutput>>;
  deleteWalkIn(walkInId: number): Promise<ApiResponse<WalkInOutput>>;
  bulkDeleteWalkIns(walkInIds: number[]): Promise<ApiResponse<WalkInOutput>>;
  deactivateServiceResource(
    id: number
  ): Promise<ApiResponse<ServiceResourceOutput>>;
  deactivateScheduleTemplate(
    id: number
  ): Promise<ApiResponse<ScheduleTemplateOutput>>;
  deleteScheduleBlockedDate(
    id: number
  ): Promise<ApiResponse<ScheduleBlockedDateOutput>>;

  // ─── ReservableService Mutations ───
  createReservableService(
    input: CreateReservableServiceInput
  ): Promise<ApiResponse<ReservableServiceOutput>>;
  updateReservableService(
    input: UpdateReservableServiceInput
  ): Promise<ApiResponse<ReservableServiceOutput>>;
  deleteReservableService(
    id: number
  ): Promise<ApiResponse<DeleteReservableServiceOutput>>;

  // ─── RefundPolicy Mutations ───
  createRefundPolicy(
    input: CreateRefundPolicyInput
  ): Promise<ApiResponse<RefundPolicyOutput>>;
  updateRefundPolicy(
    input: UpdateRefundPolicyInput
  ): Promise<ApiResponse<RefundPolicyOutput>>;
  deleteRefundPolicy(id: number): Promise<ApiResponse<RefundPolicyOutput>>;

  // ─── FuelWalkIn Mutations ───
  createFuelWalkIn(
    input: CreateFuelWalkInInput
  ): Promise<ApiResponse<FuelWalkInOutput>>;
  attachFuelPayment(
    input: AttachFuelPaymentInput
  ): Promise<ApiResponse<FuelWalkInOutput>>;
  completeFuelWalkIn(
    input: CompleteFuelWalkInInput
  ): Promise<ApiResponse<FuelWalkInOutput>>;
  updateFuelWalkInStatus(
    input: UpdateFuelWalkInStatusInput
  ): Promise<ApiResponse<FuelWalkInOutput>>;
  deleteFuelWalkIn(
    fuelWalkInId: number
  ): Promise<ApiResponse<FuelWalkInOutput>>;
  bulkDeleteFuelWalkIns(
    fuelWalkInIds: number[]
  ): Promise<ApiResponse<FuelWalkInOutput>>;
  createFuelWalkInPackage(
    input: CreateFuelWalkInPackageInput
  ): Promise<ApiResponse<FuelWalkInPackageOutput>>;
  attachPackagePayment(
    input: AttachPackagePaymentInput
  ): Promise<ApiResponse<FuelWalkInPackageOutput>>;
  updatePackageStatus(
    input: UpdatePackageStatusInput
  ): Promise<ApiResponse<FuelWalkInPackageOutput>>;

  // ─── HeatingOilDelivery Mutations ───
  createHeatingOilDelivery(
    input: CreateHeatingOilDeliveryInput
  ): Promise<ApiResponse<HeatingOilDeliveryOutput>>;
  assignDeliveryDriver(
    input: AssignDriverInput
  ): Promise<ApiResponse<HeatingOilDeliveryOutput>>;
  updateHeatingOilDeliveryStatus(
    input: UpdateHeatingOilDeliveryStatusInput
  ): Promise<ApiResponse<HeatingOilDeliveryOutput>>;
  completeHeatingOilDelivery(
    input: CompleteHeatingOilDeliveryInput
  ): Promise<ApiResponse<HeatingOilDeliveryOutput>>;
  deleteHeatingOilDelivery(
    deliveryId: number
  ): Promise<ApiResponse<HeatingOilDeliveryOutput>>;
  bulkDeleteHeatingOilDeliveries(
    deliveryIds: number[]
  ): Promise<ApiResponse<HeatingOilDeliveryOutput>>;
}

// ============================================================================
// Context 상태 타입 — Reservation
// ============================================================================

export interface ReservationFilters {
  storeId?: number;
  userId?: number;
  status?: ReservationStatus;
  isWalkIn?: boolean;
  dateFrom?: string;
  dateTo?: string;
}

export interface ReservationsState {
  reservations: Reservation[];
  currentReservation: Reservation | null;
  availableSlots: ReservationTimeSlot[];
  walkIns: WalkIn[];
  filters: ReservationFilters;
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
  isLoading: boolean;
  error: string | null;
}

export interface ReservationsContextActions {
  setReservations: (reservations: Reservation[]) => void;
  addReservation: (reservation: Reservation) => void;
  updateReservationInContext: (
    id: number,
    updates: Partial<Reservation>
  ) => void;
  removeReservation: (id: number) => void;
  setCurrentReservation: (reservation: Reservation | null) => void;
  setAvailableSlots: (slots: ReservationTimeSlot[]) => void;
  setWalkIns: (walkIns: WalkIn[]) => void;
  updateWalkInInContext: (id: number, updates: Partial<WalkIn>) => void;
  setFilters: (filters: Partial<ReservationFilters>) => void;
  clearFilters: () => void;
  setPagination: (pagination: Partial<ReservationsState['pagination']>) => void;
  setLoading: (loading: boolean) => void;
  setError: (error: string | null) => void;
  clearError: () => void;
  reset: () => void;
}

export type ReservationsContextValue = ReservationsState &
  ReservationsContextActions;

// ============================================================================
// Context 상태 타입 — FuelWalkIn
// ============================================================================

export interface FuelWalkInFilters {
  storeId?: number;
  status?: FuelWalkInStatus;
}

export interface FuelWalkInsState {
  fuelWalkIns: FuelWalkIn[];
  currentFuelWalkIn: FuelWalkIn | null;
  filters: FuelWalkInFilters;
  isLoading: boolean;
  error: string | null;
}

export interface FuelWalkInsContextActions {
  setFuelWalkIns: (items: FuelWalkIn[]) => void;
  addFuelWalkIn: (item: FuelWalkIn) => void;
  updateFuelWalkInInContext: (id: number, updates: Partial<FuelWalkIn>) => void;
  removeFuelWalkIn: (id: number) => void;
  setCurrentFuelWalkIn: (item: FuelWalkIn | null) => void;
  setFilters: (filters: Partial<FuelWalkInFilters>) => void;
  clearFilters: () => void;
  setLoading: (loading: boolean) => void;
  setError: (error: string | null) => void;
  clearError: () => void;
  reset: () => void;
}

export type FuelWalkInsContextValue = FuelWalkInsState &
  FuelWalkInsContextActions;

// ============================================================================
// Context 상태 타입 — HeatingOilDelivery
// ============================================================================

export interface HeatingOilDeliveryFilters {
  storeId?: number;
  status?: HeatingOilDeliveryStatus;
  isUrgent?: boolean;
  driverId?: number;
}

export interface HeatingOilDeliveriesState {
  deliveries: HeatingOilDelivery[];
  currentDelivery: HeatingOilDelivery | null;
  filters: HeatingOilDeliveryFilters;
  isLoading: boolean;
  error: string | null;
}

export interface HeatingOilDeliveriesContextActions {
  setDeliveries: (items: HeatingOilDelivery[]) => void;
  addDelivery: (item: HeatingOilDelivery) => void;
  updateDeliveryInContext: (
    id: number,
    updates: Partial<HeatingOilDelivery>
  ) => void;
  removeDelivery: (id: number) => void;
  setCurrentDelivery: (item: HeatingOilDelivery | null) => void;
  setFilters: (filters: Partial<HeatingOilDeliveryFilters>) => void;
  clearFilters: () => void;
  setLoading: (loading: boolean) => void;
  setError: (error: string | null) => void;
  clearError: () => void;
  reset: () => void;
}

export type HeatingOilDeliveriesContextValue = HeatingOilDeliveriesState &
  HeatingOilDeliveriesContextActions;
