import { gql } from '@apollo/client';

// ─── Fragments ───────────────────────────────────────────────────────────────

export const RESERVATION_ERROR_INFO_FIELDS = gql`
  fragment ReservationErrorInfoFields on ErrorInfo {
    code
    message
    details
  }
`;

export const RESERVATION_FIELDS = gql`
  fragment ReservationFields on Reservation {
    id
    reservationNumber
    storeId
    serviceId
    timeSlotId
    resourceId
    vehicleId
    reservedDate
    reservedStartTime
    reservedEndTime
    paymentExpiresAt
    autoCancel
    userId
    guestEmail
    customerInfo
    status
    confirmationType
    isWalkIn
    partySize
    specialRequests
    paymentId
    paymentConfirmed
    appliedRefundPolicy
    confirmedAt
    checkedInAt
    serviceStartedAt
    completedAt
    cancelledAt
    notes
    metadata
    createdById
    createdAt
    updatedAt
    deletedAt
    store {
      id
    }
    user {
      id
    }
    vehicle {
      id
    }
  }
`;

export const RESERVATION_TIME_SLOT_FIELDS = gql`
  fragment ReservationTimeSlotFields on ReservationTimeSlot {
    id
    serviceId
    resourceId
    date
    startTime
    endTime
    status
    maxCapacity
    currentBookings
    pendingBookings
    priceMultiplier
    bookingDeadline
    isAutoGenerated
    notes
    createdAt
    updatedAt
    deletedAt
  }
`;

export const SERVICE_RESOURCE_FIELDS = gql`
  fragment ServiceResourceFields on ServiceResource {
    id
    serviceId
    name
    code
    type
    capacity
    isActive
    isAvailable
    notes
    createdAt
    updatedAt
    deletedAt
  }
`;

export const SCHEDULE_TEMPLATE_FIELDS = gql`
  fragment ScheduleTemplateFields on ScheduleTemplate {
    id
    serviceId
    name
    isActive
    applicableDays
    openTime
    closeTime
    slotDuration
    maxConcurrentBookings
    autoGenerateDays
    createdById
    createdAt
    updatedAt
    deletedAt
  }
`;

export const WALK_IN_FIELDS = gql`
  fragment WalkInFields on WalkIn {
    id
    storeId
    serviceId
    resourceId
    userId
    customerName
    customerPhone
    vehicleId
    packageId
    paymentConfirmed
    status
    waitingOrder
    estimatedWaitMinutes
    arrivedAt
    calledAt
    startedAt
    completedAt
    cancelledAt
    notes
    metadata
    createdAt
    updatedAt
    deletedAt
  }
`;

export const FUEL_WALK_IN_FIELDS = gql`
  fragment FuelWalkInFields on FuelWalkIn {
    id
    storeId
    resourceId
    userId
    customerName
    customerPhone
    vehicleId
    productId
    fuelType
    requestedAmount
    actualAmount
    literAmount
    unitPrice
    isPrepaid
    paymentId
    paymentConfirmed
    packageId
    status
    arrivedAt
    paymentDoneAt
    startedAt
    completedAt
    cancelledAt
    notes
    metadata
    createdAt
    updatedAt
    deletedAt
  }
`;

export const FUEL_WALK_IN_PACKAGE_FIELDS = gql`
  fragment FuelWalkInPackageFields on FuelWalkInPackage {
    id
    storeId
    userId
    customerName
    customerPhone
    vehicleId
    includesFuel
    includesWash
    washServiceId
    isPrepaid
    paymentId
    paymentConfirmed
    status
    arrivedAt
    completedAt
    cancelledAt
    notes
    metadata
    createdAt
    updatedAt
    deletedAt
  }
`;

export const HEATING_OIL_DELIVERY_FIELDS = gql`
  fragment HeatingOilDeliveryFields on HeatingOilDelivery {
    id
    storeId
    deliveryNumber
    productId
    userId
    customerName
    customerPhone
    guestEmail
    deliveryAddress
    deliveryAddressDetail
    deliveryLatitude
    deliveryLongitude
    fuelType
    orderType
    requestedLiters
    actualLiters
    unitPrice
    tankCapacity
    tankCurrentLevel
    paymentId
    paymentConfirmed
    status
    scheduledDate
    scheduledTimeSlot
    isUrgent
    urgentRequestedAt
    urgentReason
    driverId
    driverAssignedAt
    confirmedAt
    dispatchedAt
    arrivedAt
    completedAt
    cancelledAt
    notes
    metadata
    createdAt
    updatedAt
    deletedAt
  }
`;

// ─── 신규: ReservableService Fragment + Query ─────────────────────────────────

export const RESERVABLE_SERVICE_FIELDS = gql`
  fragment ReservableServiceFields on ReservableService {
    id
    storeId
    name
    type
    serviceTypeCode
    description
    confirmationType
    slotGenerationType
    requiresPayment
    allowWalkIn
    operatingHours
    slotDuration
    maxAdvanceDays
    minAdvanceHours
    basePrice
    depositRate
    refundPolicyId
    isActive
    isAvailable
    createdById
    updatedById
    createdAt
    updatedAt
    deletedAt
  }
`;

export const FIND_RESERVABLE_SERVICES = gql`
  ${RESERVABLE_SERVICE_FIELDS}
  query FindReservableServices($input: FindReservableServicesInput!) {
    findReservableServices(input: $input) {
      success
      services {
        ...ReservableServiceFields
      }
    }
  }
`;
// ─── RefundPolicy Fragment + Queries ─────────────────────────────────────────

export const REFUND_POLICY_FIELDS = gql`
  fragment RefundPolicyFields on RefundPolicy {
    id
    name
    description
    refundRules
    allowRefund
    minimumRefundAmount
    refundFee
    noRefundConditions
    createdById
    createdAt
    updatedAt
    deletedAt
  }
`;

export const FIND_REFUND_POLICIES = gql`
  ${REFUND_POLICY_FIELDS}
  query FindRefundPolicies {
    findRefundPolicies {
      success
      refundPolicies {
        ...RefundPolicyFields
      }
    }
  }
`;

// ─── RefundPolicy Mutations ───────────────────────────────────────────────────

export const CREATE_REFUND_POLICY = gql`
  ${REFUND_POLICY_FIELDS}
  mutation CreateRefundPolicy($input: CreateRefundPolicyInput!) {
    createRefundPolicy(input: $input) {
      success
      refundPolicy {
        ...RefundPolicyFields
      }
      message
    }
  }
`;

export const UPDATE_REFUND_POLICY = gql`
  ${REFUND_POLICY_FIELDS}
  mutation UpdateRefundPolicy($input: UpdateRefundPolicyInput!) {
    updateRefundPolicy(input: $input) {
      success
      refundPolicy {
        ...RefundPolicyFields
      }
      message
    }
  }
`;

export const DELETE_REFUND_POLICY = gql`
  mutation DeleteRefundPolicy($id: Int!) {
    deleteRefundPolicy(id: $id) {
      success
      message
    }
  }
`;

// ─── Reservation Queries ──────────────────────────────────────────────────────

export const GET_RESERVATION = gql`
  ${RESERVATION_FIELDS}
  query FindReservationNew($id: Int!) {
    findReservationNew(id: $id) {
      ...ReservationFields
    }
  }
`;

// ─── ReservableService Mutations ──────────────────────────────────────────────

export const CREATE_RESERVABLE_SERVICE = gql`
  ${RESERVABLE_SERVICE_FIELDS}
  mutation CreateReservableService($input: CreateReservableServiceInput!) {
    createReservableService(input: $input) {
      success
      service {
        ...ReservableServiceFields
      }
      message
    }
  }
`;

export const UPDATE_RESERVABLE_SERVICE = gql`
  ${RESERVABLE_SERVICE_FIELDS}
  mutation UpdateReservableService($input: UpdateReservableServiceInput!) {
    updateReservableService(input: $input) {
      success
      service {
        ...ReservableServiceFields
      }
      message
    }
  }
`;

export const DELETE_RESERVABLE_SERVICE = gql`
  mutation DeleteReservableService($id: Int!) {
    deleteReservableService(id: $id) {
      success
      message
    }
  }
`;

export const LIST_RESERVATIONS = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${RESERVATION_FIELDS}
  query FindReservationsNew($input: FindReservationsInput!) {
    findReservationsNew(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      reservations {
        ...ReservationFields
      }
      total
      page
      limit
      totalPages
    }
  }
`;

export const FIND_AVAILABLE_SLOTS = gql`
  ${RESERVATION_TIME_SLOT_FIELDS}
  query FindAvailableSlots($serviceId: Int!, $date: String!) {
    findAvailableSlots(serviceId: $serviceId, date: $date) {
      ...ReservationTimeSlotFields
    }
  }
`;

export const FIND_SERVICE_RESOURCES = gql`
  ${SERVICE_RESOURCE_FIELDS}
  query FindServiceResources($serviceId: Int!) {
    findServiceResources(serviceId: $serviceId) {
      ...ServiceResourceFields
    }
  }
`;

export const FIND_SCHEDULE_TEMPLATES = gql`
  ${SCHEDULE_TEMPLATE_FIELDS}
  query FindScheduleTemplates($serviceId: Int!) {
    findScheduleTemplates(serviceId: $serviceId) {
      ...ScheduleTemplateFields
    }
  }
`;

// ← 신규 추가
export const SCHEDULE_BLOCKED_DATE_FIELDS = gql`
  fragment ScheduleBlockedDateFields on ScheduleBlockedDate {
    id
    serviceId
    date
    reason
    isFullDay
    blockedStartTime
    blockedEndTime
    createdById
    createdAt
    updatedAt
  }
`;

// ← findScheduleBlockedDates: 인자 구조 변경 (input 객체로)
export const FIND_SCHEDULE_BLOCKED_DATES = gql`
  ${SCHEDULE_BLOCKED_DATE_FIELDS}
  query FindScheduleBlockedDates($input: FindScheduleBlockedDatesInput!) {
    findScheduleBlockedDates(input: $input) {
      success
      blockedDates {
        ...ScheduleBlockedDateFields
      }
      total
    }
  }
`;

// ← CREATE: createdById 제거, date가 String으로 변경됨 (쿼리 자체는 동일)
// 기존 CREATE_SCHEDULE_BLOCKED_DATE 유지

// ← 신규: UPDATE
export const UPDATE_SCHEDULE_BLOCKED_DATE = gql`
  ${SCHEDULE_BLOCKED_DATE_FIELDS}
  mutation UpdateScheduleBlockedDate($input: UpdateScheduleBlockedDateInput!) {
    updateScheduleBlockedDate(input: $input) {
      success
      error {
        code
        message
        details
      }
      blockedDate {
        ...ScheduleBlockedDateFields
      }
      message
    }
  }
`;

// ← 신규: BULK DELETE
export const BULK_DELETE_SCHEDULE_BLOCKED_DATES = gql`
  mutation BulkDeleteScheduleBlockedDates($ids: [Int!]!) {
    bulkDeleteScheduleBlockedDates(ids: $ids) {
      success
      error {
        code
        message
        details
      }
      message
    }
  }
`;

export const FIND_WALK_INS = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${WALK_IN_FIELDS}
  query FindWalkIns($input: FindWalkInsInput!) {
    findWalkIns(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      walkIns {
        ...WalkInFields
      }
      total
    }
  }
`;

// ─── FuelWalkIn Queries ───────────────────────────────────────────────────────

export const FIND_FUEL_WALK_INS = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${FUEL_WALK_IN_FIELDS}
  query FindFuelWalkIns($input: FindFuelWalkInsInput!) {
    findFuelWalkIns(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      fuelWalkIns {
        ...FuelWalkInFields
      }
      total
    }
  }
`;

// ─── HeatingOilDelivery Queries ───────────────────────────────────────────────

export const FIND_HEATING_OIL_DELIVERIES = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${HEATING_OIL_DELIVERY_FIELDS}
  query FindHeatingOilDeliveries($input: FindHeatingOilDeliveriesInput!) {
    findHeatingOilDeliveries(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      deliveries {
        ...HeatingOilDeliveryFields
      }
      total
    }
  }
`;

// ─── Reservation Mutations ────────────────────────────────────────────────────

export const CREATE_RESERVATION = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${RESERVATION_FIELDS}
  mutation CreateReservationNew($input: CreateReservationInput!) {
    createReservationNew(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      reservations {
        ...ReservationFields
      }
      reservation {
        ...ReservationFields
      }
      message
    }
  }
`;

export const UPDATE_RESERVATION_STATUS = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${RESERVATION_FIELDS}
  mutation UpdateReservationStatus($input: UpdateReservationStatusInput!) {
    updateReservationStatus(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      reservation {
        ...ReservationFields
      }
      message
    }
  }
`;

export const CANCEL_RESERVATION = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${RESERVATION_FIELDS}
  mutation CancelReservationNew($input: CancelReservationInput!) {
    cancelReservationNew(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      reservation {
        ...ReservationFields
      }
      message
      refundRequested
    }
  }
`;

export const CHECK_IN_RESERVATION = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${RESERVATION_FIELDS}
  mutation CheckInReservationNew($input: CheckInReservationInput!) {
    checkInReservationNew(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      reservation {
        ...ReservationFields
      }
      message
    }
  }
`;

export const CHECK_OUT_RESERVATION = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${RESERVATION_FIELDS}
  mutation CheckOutReservationNew($input: CheckOutReservationInput!) {
    checkOutReservationNew(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      reservation {
        ...ReservationFields
      }
      message
    }
  }
`;

export const REVIEW_RESERVATION_APPROVAL = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  mutation ReviewReservationApproval($input: ReviewReservationApprovalInput!) {
    reviewReservationApproval(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      approval {
        id
        reservationId
        status
        reviewedBy
        reviewedAt
        reason
        autoApproveAt
        createdAt
        updatedAt
      }
      message
    }
  }
`;

export const CREATE_WALK_IN = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${WALK_IN_FIELDS}
  mutation CreateWalkIn($input: CreateWalkInInput!) {
    createWalkIn(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      walkIn {
        ...WalkInFields
      }
      message
    }
  }
`;

export const UPDATE_WALK_IN_STATUS = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${WALK_IN_FIELDS}
  mutation UpdateWalkInStatus($input: UpdateWalkInStatusInput!) {
    updateWalkInStatus(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      walkIn {
        ...WalkInFields
      }
      message
    }
  }
`;

export const DELETE_WALK_IN = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${WALK_IN_FIELDS}
  mutation DeleteWalkIn($walkInId: Int!) {
    deleteWalkIn(walkInId: $walkInId) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      walkIn {
        ...WalkInFields
      }
      message
    }
  }
`;

export const BULK_DELETE_WALK_INS = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  mutation BulkDeleteWalkIns($walkInIds: [Int!]!) {
    bulkDeleteWalkIns(walkInIds: $walkInIds) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      message
    }
  }
`;

export const GENERATE_SLOTS = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${RESERVATION_TIME_SLOT_FIELDS}
  mutation GenerateSlots($input: GenerateSlotsInput!) {
    generateSlots(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      slots {
        ...ReservationTimeSlotFields
      }
      generatedCount
      message
    }
  }
`;

export const CREATE_SCHEDULE_TEMPLATE = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${SCHEDULE_TEMPLATE_FIELDS}
  mutation CreateScheduleTemplate($input: CreateScheduleTemplateInput!) {
    createScheduleTemplate(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      template {
        ...ScheduleTemplateFields
      }
      message
    }
  }
`;

export const CREATE_SERVICE_RESOURCE = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${SERVICE_RESOURCE_FIELDS}
  mutation CreateServiceResource($input: CreateServiceResourceInput!) {
    createServiceResource(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      resource {
        ...ServiceResourceFields
      }
      message
    }
  }
`;

export const UPDATE_SERVICE_RESOURCE = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${SERVICE_RESOURCE_FIELDS}
  mutation UpdateServiceResource($input: UpdateServiceResourceInput!) {
    updateServiceResource(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      resource {
        ...ServiceResourceFields
      }
      message
    }
  }
`;

export const DELETE_RESERVATION = gql`
  mutation DeleteReservation($reservationId: Int!) {
    deleteReservation(reservationId: $reservationId) {
      success
      message
    }
  }
`;

export const BULK_DELETE_RESERVATIONS = gql`
  mutation BulkDeleteReservations($reservationIds: [Int!]!) {
    bulkDeleteReservations(reservationIds: $reservationIds) {
      success
      message
    }
  }
`;

export const DEACTIVATE_SERVICE_RESOURCE = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${SERVICE_RESOURCE_FIELDS}
  mutation DeactivateServiceResource($id: Int!) {
    deactivateServiceResource(id: $id) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      resource {
        ...ServiceResourceFields
      }
      message
    }
  }
`;

export const DEACTIVATE_SCHEDULE_TEMPLATE = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${SCHEDULE_TEMPLATE_FIELDS}
  mutation DeactivateScheduleTemplate($id: Int!) {
    deactivateScheduleTemplate(id: $id) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      template {
        ...ScheduleTemplateFields
      }
      message
    }
  }
`;

export const DELETE_SCHEDULE_BLOCKED_DATE = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  mutation DeleteScheduleBlockedDate($id: Int!) {
    deleteScheduleBlockedDate(id: $id) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      message
    }
  }
`;

export const CREATE_SCHEDULE_BLOCKED_DATE = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  mutation CreateScheduleBlockedDate($input: CreateScheduleBlockedDateInput!) {
    createScheduleBlockedDate(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      blockedDate {
        id
        serviceId
        date
        reason
        isFullDay
        blockedStartTime
        blockedEndTime
        createdById
        createdAt
      }
      message
    }
  }
`;

// ─── FuelWalkIn Mutations ─────────────────────────────────────────────────────

export const CREATE_FUEL_WALK_IN = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${FUEL_WALK_IN_FIELDS}
  mutation CreateFuelWalkIn($input: CreateFuelWalkInInput!) {
    createFuelWalkIn(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      fuelWalkIn {
        ...FuelWalkInFields
      }
      message
    }
  }
`;

export const ATTACH_FUEL_PAYMENT = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${FUEL_WALK_IN_FIELDS}
  mutation AttachFuelPayment($input: AttachFuelPaymentInput!) {
    attachFuelPayment(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      fuelWalkIn {
        ...FuelWalkInFields
      }
      message
    }
  }
`;

export const COMPLETE_FUEL_WALK_IN = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${FUEL_WALK_IN_FIELDS}
  mutation CompleteFuelWalkIn($input: CompleteFuelWalkInInput!) {
    completeFuelWalkIn(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      fuelWalkIn {
        ...FuelWalkInFields
      }
      message
    }
  }
`;

export const UPDATE_FUEL_WALK_IN_STATUS = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${FUEL_WALK_IN_FIELDS}
  mutation UpdateFuelWalkInStatus($input: UpdateFuelWalkInStatusInput!) {
    updateFuelWalkInStatus(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      fuelWalkIn {
        ...FuelWalkInFields
      }
      message
    }
  }
`;

export const DELETE_FUEL_WALK_IN = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  mutation DeleteFuelWalkIn($fuelWalkInId: Int!) {
    deleteFuelWalkIn(fuelWalkInId: $fuelWalkInId) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      message
    }
  }
`;

export const BULK_DELETE_FUEL_WALK_INS = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  mutation BulkDeleteFuelWalkIns($fuelWalkInIds: [Int!]!) {
    bulkDeleteFuelWalkIns(fuelWalkInIds: $fuelWalkInIds) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      message
    }
  }
`;

export const CREATE_FUEL_WALK_IN_PACKAGE = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${FUEL_WALK_IN_PACKAGE_FIELDS}
  mutation CreateFuelWalkInPackage($input: CreateFuelWalkInPackageInput!) {
    createFuelWalkInPackage(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      package {
        ...FuelWalkInPackageFields
      }
      message
    }
  }
`;

export const ATTACH_PACKAGE_PAYMENT = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${FUEL_WALK_IN_PACKAGE_FIELDS}
  mutation AttachPackagePayment($input: AttachPackagePaymentInput!) {
    attachPackagePayment(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      package {
        ...FuelWalkInPackageFields
      }
      message
    }
  }
`;

export const UPDATE_PACKAGE_STATUS = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${FUEL_WALK_IN_PACKAGE_FIELDS}
  mutation UpdatePackageStatus($input: UpdatePackageStatusInput!) {
    updatePackageStatus(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      package {
        ...FuelWalkInPackageFields
      }
      message
    }
  }
`;

// ─── HeatingOilDelivery Mutations ─────────────────────────────────────────────

export const CREATE_HEATING_OIL_DELIVERY = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${HEATING_OIL_DELIVERY_FIELDS}
  mutation CreateHeatingOilDelivery($input: CreateHeatingOilDeliveryInput!) {
    createHeatingOilDelivery(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      delivery {
        ...HeatingOilDeliveryFields
      }
      message
    }
  }
`;

export const ASSIGN_DELIVERY_DRIVER = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${HEATING_OIL_DELIVERY_FIELDS}
  mutation AssignDeliveryDriver($input: AssignDriverInput!) {
    assignDeliveryDriver(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      delivery {
        ...HeatingOilDeliveryFields
      }
      message
    }
  }
`;

export const UPDATE_HEATING_OIL_DELIVERY_STATUS = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${HEATING_OIL_DELIVERY_FIELDS}
  mutation UpdateHeatingOilDeliveryStatus(
    $input: UpdateHeatingOilDeliveryStatusInput!
  ) {
    updateHeatingOilDeliveryStatus(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      delivery {
        ...HeatingOilDeliveryFields
      }
      message
    }
  }
`;

export const COMPLETE_HEATING_OIL_DELIVERY = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  ${HEATING_OIL_DELIVERY_FIELDS}
  mutation CompleteHeatingOilDelivery(
    $input: CompleteHeatingOilDeliveryInput!
  ) {
    completeHeatingOilDelivery(input: $input) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      delivery {
        ...HeatingOilDeliveryFields
      }
      message
    }
  }
`;

export const DELETE_HEATING_OIL_DELIVERY = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  mutation DeleteHeatingOilDelivery($deliveryId: Int!) {
    deleteHeatingOilDelivery(deliveryId: $deliveryId) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      message
    }
  }
`;

export const BULK_DELETE_HEATING_OIL_DELIVERIES = gql`
  ${RESERVATION_ERROR_INFO_FIELDS}
  mutation BulkDeleteHeatingOilDeliveries($deliveryIds: [Int!]!) {
    bulkDeleteHeatingOilDeliveries(deliveryIds: $deliveryIds) {
      success
      error {
        ...ReservationErrorInfoFields
      }
      message
    }
  }
`;
